version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Waban123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

  authapi:
    image: dunjanesic13/authapi:latest
    ports:
      - "5001:8080"
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=UserDB;User Id=sa;Password=Waban123!;TrustServerCertificate=True;

  horseapi:
    image: dunjanesic13/horseapi:latest
    ports:
      - "5002:8080"
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=HorseDB;User Id=sa;Password=Waban123!;TrustServerCertificate=True;

  sessionapi:
    image: dunjanesic13/sessionapi:latest
    ports:
      - "5003:8080"
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=SessionDB;User Id=sa;Password=Waban123!;TrustServerCertificate=True;

  trainerapi:
    image: dunjanesic13/trainerapi:latest
    ports:
      - "5004:8080"
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=TrainerDB;User Id=sa;Password=Waban123!;TrustServerCertificate=True;

volumes:
  sqlvolume:
