// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Services.SessionAPI.Infrastructure;

#nullable disable

namespace Services.SessionAPI.Migrations
{
    [DbContext(typeof(SessionDbContext))]
    [Migration("20250321115533_AddedStudentName")]
    partial class AddedStudentName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Services.SessionAPI.Domain.SessionAssigned", b =>
                {
                    b.Property<int>("SessionAssignedID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionAssignedID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrainerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SessionAssignedID");

                    b.ToTable("SessionAssigned");
                });

            modelBuilder.Entity("Services.SessionAPI.Domain.SessionDetails", b =>
                {
                    b.Property<int>("SessionDetailsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionDetailsID"));

                    b.Property<int>("HorseID")
                        .HasColumnType("int");

                    b.Property<bool>("IsOnPackage")
                        .HasColumnType("bit");

                    b.Property<int>("SessionAssignedID")
                        .HasColumnType("int");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SessionDetailsID");

                    b.HasIndex("SessionAssignedID");

                    b.ToTable("SessionDetails");
                });

            modelBuilder.Entity("Services.SessionAPI.Domain.SessionDetails", b =>
                {
                    b.HasOne("Services.SessionAPI.Domain.SessionAssigned", "SessionAsigned")
                        .WithMany()
                        .HasForeignKey("SessionAssignedID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessionAsigned");
                });
#pragma warning restore 612, 618
        }
    }
}
