// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Services.HorseAPI.Infrastructure;

#nullable disable

namespace Services.HorseAPI.Migrations
{
    [DbContext(typeof(HorseDbContext))]
    [Migration("20250320161249_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Services.HorseAPI.Domain.Horse", b =>
                {
                    b.Property<int>("HorseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HorseID"));

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HorseID");

                    b.ToTable("Horses");

                    b.HasData(
                        new
                        {
                            HorseID = 1,
                            Breed = "Thoroughbred",
                            DateOfBirth = new DateTime(2016, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Waban"
                        },
                        new
                        {
                            HorseID = 2,
                            Breed = "Arabian",
                            DateOfBirth = new DateTime(2016, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Silver Static"
                        },
                        new
                        {
                            HorseID = 3,
                            Breed = "Quarter Horse",
                            DateOfBirth = new DateTime(2014, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Beba"
                        },
                        new
                        {
                            HorseID = 4,
                            Breed = "Paint Horse",
                            DateOfBirth = new DateTime(2017, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sena"
                        },
                        new
                        {
                            HorseID = 5,
                            Breed = "Mustang",
                            DateOfBirth = new DateTime(2018, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Crystal Night"
                        },
                        new
                        {
                            HorseID = 6,
                            Breed = "Pony",
                            DateOfBirth = new DateTime(2015, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Princess"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
