name: Build, Test and Analyze

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.102

      - name: Install SonarScanner for .NET
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Restore dependencies
        run: dotnet restore

      - name: Begin SonarCloud analysis
        run: |
          dotnet sonarscanner begin \
            /k:"DunjaNesic_Microservices-HorseRidingSchool" \
            /o:"dunjanesic" \
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.host.url="https://sonarcloud.io"

      - name: Build solution
        run: dotnet build --no-restore

      - name: Run unit tests
        run: dotnet test --no-build --verbosity normal

      - name: End SonarQube analysis
        run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push authapi image
        run: |
          docker build -t dunjanesic13/authapi:latest -f Services.AuthAPI/Dockerfile Services.AuthAPI
          docker push dunjanesic13/authapi:latest

      - name: Build and push horseapi image
        run: |
          docker build -t dunjanesic13/horseapi:latest -f Services.HorseAPI/Dockerfile Services.HorseAPI
          docker push dunjanesic13/horseapi:latest

      - name: Build and push sessionapi image
        run: |
          docker build -t dunjanesic13/sessionapi:latest -f Services.SessionAPI/Dockerfile Services.SessionAPI
          docker push dunjanesic13/sessionapi:latest

      - name: Build and push trainerapi image
        run: |
          docker build -t dunjanesic13/trainerapi:latest -f Services.TrainerAPI/Dockerfile Services.TrainerAPI
          docker push dunjanesic13/trainerapi:latest
